
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int QUE = 12;
  public static final int MAIS = 2;
  public static final int GUARDAR = 8;
  public static final int QUADRADO = 6;
  public static final int MENOS = 3;
  public static final int APAR = 10;
  public static final int RAIZ = 7;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 14;
  public static final int ID = 13;
  public static final int EM = 9;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int FPAR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIV",
  "QUADRADO",
  "RAIZ",
  "GUARDAR",
  "EM",
  "APAR",
  "FPAR",
  "QUE",
  "ID",
  "NUMERO"
  };
}

