
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int FPAR = 12;
  public static final int MENOS = 4;
  public static final int MENOR = 18;
  public static final int ENTAO = 20;
  public static final int RAIZ = 8;
  public static final int IGUAL = 16;
  public static final int QUE = 13;
  public static final int APAR = 11;
  public static final int ID = 14;
  public static final int EOL = 2;
  public static final int MAIS = 3;
  public static final int GUARDAR = 9;
  public static final int EOF = 0;
  public static final int A = 17;
  public static final int DIV = 6;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int MAIOR = 15;
  public static final int SE = 19;
  public static final int EM = 10;
  public static final int VEZES = 5;
  public static final int QUADRADO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EOL",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIV",
  "QUADRADO",
  "RAIZ",
  "GUARDAR",
  "EM",
  "APAR",
  "FPAR",
  "QUE",
  "ID",
  "MAIOR",
  "IGUAL",
  "A",
  "MENOR",
  "SE",
  "ENTAO",
  "NUMERO"
  };
}

